In [50]:
import pandas as pd

In [51]:
df= pd.read_csv("Marks.csv")

In [52]:
df

   Student_Name   Math  Science  English  Computer  Attendance
0     Student_1   48.0     43.0      NaN      57.0        91.0
1     Student_2   88.0      NaN     75.0      91.0        84.0
2     Student_3    NaN     61.0     51.0      81.0        61.0
3     Student_4   97.0     84.0     72.0       NaN        60.0
4     Student_5   84.0     92.0     62.0      96.0         NaN
5     Student_6    NaN     48.0     65.0      51.0        61.0
6     Student_7   41.0      NaN     69.0      93.0        73.0
7     Student_8   67.0     38.0     78.0      64.0        88.0
8     Student_9  100.0     98.0      NaN      64.0        82.0
9    Student_10    NaN     63.0     93.0      79.0        78.0
10   Student_11   99.0      NaN     71.0      85.0        66.0
11   Student_12   51.0     72.0     52.0       NaN        81.0
12   Student_13    NaN     99.0     72.0      82.0        72.0
13   Student_14   59.0     71.0     82.0      81.0         NaN
14   Student_15   65.0     39.0     75.0      65.0        85.0
15   Student_16   66.0      NaN     68.0      85.0        83.0
16   Student_17   45.0     91.0      NaN      82.0        66.0
17   Student_18   89.0     55.0     78.0      75.0        83.0
18   Student_19    NaN     38.0     75.0      52.0        79.0
19   Student_20   85.0     85.0     86.0       NaN        70.0
20   Student_21   72.0      NaN     45.0      99.0        72.0
21   Student_22   74.0     64.0     70.0      82.0         NaN
22   Student_23    NaN     80.0     74.0      67.0        95.0
23   Student_24   78.0     35.0     69.0     100.0        92.0
24   Student_25   91.0     51.0      NaN      99.0        95.0
25   Student_26   53.0      NaN     48.0      80.0        83.0
26   Student_27   76.0     60.0     77.0      76.0        91.0
27   Student_28    NaN     80.0     71.0      72.0        60.0
28   Student_29   74.0     77.0     74.0       NaN        61.0
29   Student_30   91.0     64.0     85.0      61.0         NaN
30   Student_31   77.0      NaN    100.0      55.0        95.0
31   Student_32    NaN     67.0     47.0      93.0        64.0
32   Student_33   45.0     37.0      NaN      50.0        77.0
33   Student_34   55.0     69.0     52.0      89.0        71.0
34   Student_35   62.0     72.0     49.0      60.0        70.0
35   Student_36   56.0      NaN     87.0      67.0        78.0
36   Student_37   69.0     76.0     76.0       NaN        67.0
37   Student_38    NaN     74.0     69.0      71.0        86.0
38   Student_39   90.0     59.0     61.0      56.0         NaN
39   Student_40   97.0    100.0     58.0      88.0        87.0
40   Student_41   92.0      NaN     59.0      51.0        85.0
41   Student_42    NaN     39.0     91.0      60.0        88.0
42   Student_43   85.0     99.0     88.0      77.0        94.0
43   Student_44   93.0     63.0     85.0      94.0        93.0
44   Student_45   68.0     63.0      NaN      91.0        61.0
45   Student_46   65.0     76.0     87.0       NaN        87.0
46   Student_47   43.0     73.0     53.0      63.0         NaN
47   Student_48   59.0     44.0     99.0      54.0        79.0
48   Student_11   99.0      NaN     71.0      85.0        66.0
49   Student_21   72.0      NaN     45.0      99.0        72.0

In [53]:
df.shape

(50, 6)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_Name  50 non-null     object
 1   Math          40 non-null     float64
 2   Science       39 non-null     float64
 3   English       44 non-null     float64
 4   Computer      44 non-null     float64
 5   Attendance    44 non-null     float64
dtypes: float64(5), object(1)
memory usage: 2.5+ KB

In [55]:
df.head()

  Student_Name  Math  Science  English  Computer  Attendance
0    Student_1  48.0     43.0      NaN      57.0        91.0
1    Student_2  88.0      NaN     75.0      91.0        84.0
2    Student_3   NaN     61.0     51.0      81.0        61.0
3    Student_4  97.0     84.0     72.0       NaN        60.0
4    Student_5  84.0     92.0     62.0      96.0         NaN

In [56]:
df.tail()

   Student_Name  Math  Science  English  Computer  Attendance
45   Student_46  65.0     76.0     87.0       NaN        87.0
46   Student_47  43.0     73.0     53.0      63.0         NaN
47   Student_48  59.0     44.0     99.0      54.0        79.0
48   Student_11  99.0      NaN     71.0      85.0        66.0
49   Student_21  72.0      NaN     45.0      99.0        72.0

In [57]:
df.describe()

             Math     Science     English    Computer  Attendance
count   40.000000   39.000000   44.000000   44.000000   44.000000
mean    73.000000   66.641026   70.772727   75.500000   78.000000
std     17.727279   19.137298   14.636469   15.515184   11.214608
min     41.000000   35.000000   45.000000   50.000000   60.000000
25%     59.000000   53.000000   60.500000   62.500000   69.250000
50%     73.000000   67.000000   71.500000   78.000000   79.000000
75%     89.250000   78.500000   79.000000   88.250000   87.000000
max    100.000000  100.000000  100.000000  100.000000   95.000000

In [61]:
data=pd.read_excel("financial_practice.xlsx")

In [62]:
data

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
0,1001,2026-01-01,Anu,Laptop,Electronics,2,90000,12000,UPI
1,1002,2026-01-02,Rahul,Mobile,Electronics,1,35000,5000,Card
2,1003,2026-01-03,Meena,Tablet,Electronics,3,45000,7000,Cash
3,1004,2026-01-04,Arjun,Monitor,Electronics,2,30000,4500,UPI
4,1005,2026-01-05,Priya,Keyboard,Accessories,5,7500,1500,Card
5,1006,2026-01-06,Vishnu,Mouse,Accessories,4,4000,800,Cash
6,1007,2026-01-07,Neha,Printer,Office,1,18000,3000,UPI
7,1008,2026-01-08,Akhil,Laptop,Electronics,1,55000,8000,Card
8,1009,2026-01-09,Sneha,Mobile,Electronics,2,36000,5500,UPI
9,1010,2026-01-10,Rohan,Tablet,Electronics,3,42000,6500,Cash
10,1011,2026-01-11,Diya,Monitor,Electronics,2,28000,4200,Card
11,1012,2026-01-12,Kiran,Keyboard,Accessories,6,9000,1800,UPI
12,1013,2026-01-13,Asha,Mouse,Accessories,5,5000,1000,Cash
13,1014,2026-01-14,Nikhil,Printer,Office,2,22000,3500,Card
14,1015,2026-01-15,Pooja,Laptop,Electronics,1,60000,9000,UPI
15,1016,2026-01-16,Manu,Mobile,Electronics,2,38000,6000,Card
16,1017,2026-01-17,Lakshmi,Tablet,Electronics,4,48000,7500,Cash
17,1018,2026-01-18,Aditya,Monitor,Electronics,1,32000,4800,UPI
18,1019,2026-01-19,Anjali,Keyboard,Accessories,5,8000,1600,Card
19,1020,2026-01-20,Suresh,Mouse,Accessories,3,4500,900,Cash
20,1021,2026-01-21,Divya,Printer,Office,2,20000,3200,UPI
21,1022,2026-01-22,Vivek,Laptop,Electronics,1,70000,10000,Card
22,1023,2026-01-23,Reshma,Mobile,Electronics,2,34000,5200,Cash
23,1024,2026-01-24,Hari,Tablet,Electronics,3,46000,7000,UPI
24,1025,2026-01-25,Amal,Monitor,Electronics,2,29000,4300,Card

data.shape

In [63]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  25 non-null     int64
 1   Date            25 non-null     object
 2   Customer        25 non-null     object
 3   Product         25 non-null     object
 4   Category        25 non-null     object
 5   Quantity        25 non-null     int64
 6   Sales_Amount    25 non-null     int64
 7   Profit          25 non-null     int64
 8   Payment_Mode    25 non-null     object
dtypes: int64(4), object(5)
memory usage: 1.9+ KB

In [64]:
data.head()

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
0,1001,2026-01-01,Anu,Laptop,Electronics,2,90000,12000,UPI
1,1002,2026-01-02,Rahul,Mobile,Electronics,1,35000,5000,Card
2,1003,2026-01-03,Meena,Tablet,Electronics,3,45000,7000,Cash
3,1004,2026-01-04,Arjun,Monitor,Electronics,2,30000,4500,UPI
4,1005,2026-01-05,Priya,Keyboard,Accessories,5,7500,1500,Card

In [65]:
data.tail()

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
20,1021,2026-01-21,Divya,Printer,Office,2,20000,3200,UPI
21,1022,2026-01-22,Vivek,Laptop,Electronics,1,70000,10000,Card
22,1023,2026-01-23,Reshma,Mobile,Electronics,2,34000,5200,Cash
23,1024,2026-01-24,Hari,Tablet,Electronics,3,46000,7000,UPI
24,1025,2026-01-25,Amal,Monitor,Electronics,2,29000,4300,Card

In [66]:
data.tail()

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
20,1021,2026-01-21,Divya,Printer,Office,2,20000,3200,UPI
21,1022,2026-01-22,Vivek,Laptop,Electronics,1,70000,10000,Card
22,1023,2026-01-23,Reshma,Mobile,Electronics,2,34000,5200,Cash
23,1024,2026-01-24,Hari,Tablet,Electronics,3,46000,7000,UPI
24,1025,2026-01-25,Amal,Monitor,Electronics,2,29000,4300,Card

In [67]:
data.describe()

       Transaction_ID  Quantity  Sales_Amount        Profit
count       25.000000  25.00000     25.000000     25.000000
mean      1013.000000   2.60000  32640.000000   4952.000000
std          7.359801   1.47196  21737.314308   2973.090424
min       1001.000000   1.00000   4000.000000    800.000000
25%       1007.000000   2.00000  18000.000000   3000.000000
50%       1013.000000   2.00000  32000.000000   4800.000000
75%       1019.000000   3.00000  45000.000000   7000.000000
max       1025.000000   6.00000  90000.000000  12000.000000

In [70]:
table=pd.read_json("financial_practice")

In [71]:
table

,Transaction_ID,Date,Customer,Product,Category,Quantity,Sales_Amount,Profit,Payment_Mode
0,1001,2026-01-01,Anu,Laptop,Electronics,2,90000,12000,UPI
1,1002,2026-01-02,Rahul,Mobile,Electronics,1,35000,5000,Card
2,1003,2026-01-03,Meena,Tablet,Electronics,3,45000,7000,Cash
3,1004,2026-01-04,Arjun,Monitor,Electronics,2,30000,4500,UPI
4,1005,2026-01-05,Priya,Keyboard,Accessories,5,7500,1500,Card
5,1006,2026-01-06,Vishnu,Mouse,Accessories,4,4000,800,Cash
6,1007,2026-01-07,Neha,Printer,Office,1,18000,3000,UPI
7,1008,2026-01-08,Akhil,Laptop,Electronics,1,55000,8000,Card
8,1009,2026-01-09,Sneha,Mobile,Electronics,2,36000,5500,UPI
9,1010,2026-01-10,Rohan,Tablet,Electronics,3,42000,6500,Cash
10,1011,2026-01-11,Diya,Monitor,Electronics,2,28000,4200,Card
11,1012,2026-01-12,Kiran,Keyboard,Accessories,6,9000,1800,UPI
12,1013,2026-01-13,Asha,Mouse,Accessories,5,5000,1000,Cash
13,1014,2026-01-14,Nikhil,Printer,Office,2,22000,3500,Card
14,1015,2026-01-15,Pooja,Laptop,Electronics,1,60000,9000,UPI
15,1016,2026-01-16,Manu,Mobile,Electronics,2,38000,6000,Card
16,1017,2026-01-17,Lakshmi,Tablet,Electronics,4,48000,7500,Cash
17,1018,2026-01-18,Aditya,Monitor,Electronics,1,32000,4800,UPI
18,1019,2026-01-19,Anjali,Keyboard,Accessories,5,8000,1600,Card
19,1020,2026-01-20,Suresh,Mouse,Accessories,3,4500,900,Cash
20,1021,2026-01-21,Divya,Printer,Office,2,20000,3200,UPI
21,1022,2026-01-22,Vivek,Laptop,Electronics,1,70000,10000,Card
22,1023,2026-01-23,Reshma,Mobile,Electronics,2,34000,5200,Cash
23,1024,2026-01-24,Hari,Tablet,Electronics,3,46000,7000,UPI
24,1025,2026-01-25,Amal,Monitor,Electronics,2,29000,4300,Card

In [89]:
table.shape

(50, 6)

In [90]:
table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_Name  50 non-null     object
 1   Math          40 non-null     float64
 2   Science       39 non-null     float64
 3   English       44 non-null     float64
 4   Computer      44 non-null     float64
 5   Attendance    44 non-null     float64
dtypes: float64(5), object(1)
memory usage: 2.5+ KB

In [91]:
table.head()

  Student_Name  Math  Science  English  Computer  Attendance
0    Student_1  48.0     43.0      NaN      57.0        91.0
1    Student_2  88.0      NaN     75.0      91.0        84.0
2    Student_3   NaN     61.0     51.0      81.0        61.0
3    Student_4  97.0     84.0     72.0       NaN        60.0
4    Student_5  84.0     92.0     62.0      96.0         NaN

In [92]:
table.tail()

   Student_Name  Math  Science  English  Computer  Attendance
45   Student_46  65.0     76.0     87.0       NaN        87.0
46   Student_47  43.0     73.0     53.0      63.0         NaN
47   Student_48  59.0     44.0     99.0      54.0        79.0
48   Student_11  99.0      NaN     71.0      85.0        66.0
49   Student_21  72.0      NaN     45.0      99.0        72.0

In [94]:
table.describe()

             Math     Science     English    Computer  Attendance
count   40.000000   39.000000   44.000000   44.000000   44.000000
mean    73.000000   66.641026   70.772727   75.500000   78.000000
std     17.727279   19.137298   14.636469   15.515184   11.214608
min     41.000000   35.000000   45.000000   50.000000   60.000000
25%     59.000000   53.000000   60.500000   62.500000   69.250000
50%     73.000000   67.000000   71.500000   78.000000   79.000000
75%     89.250000   78.500000   79.000000   88.250000   87.000000
max    100.000000  100.000000  100.000000  100.000000   95.000000

In [95]:
marks=pd.Series([82,96,85,78,98])
print(marks)

0    82
1    96
2    85
3    78
4    98
dtype: int64

In [96]:
import pandas as pd
data={
    "Name":["Rahul","Sonaia","deepu","gangha","suresh","kirthi"],
    "Marks":[98,88,90,80,85,99]
}
df=pd.DataFrame(data)
print(df)

     Name  Marks
0   Rahul     98
1  Sonaia     88
2   deepu     90
3  gangha     80
4  suresh     85
5  kirthi     99